# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlockApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'IQKeyboardManagerSwift'
  # Pods for FlockApp

  target 'FlockAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlockAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
